### ISSUE TITLE
Support filtering Slack notification

### ISSUE THREAD

**Issue by kiootic** [oursky/github-actions-manager#16]
`/gha subscribe <repo> <conclusions>`

`conclusion`: `cancelled`, `failure`, `success`, `timed_out`, etc, ref: https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run

For example:
- subscribe only successful runs: `/gha subscribe oursky/github-actions-manager success`
- subscribe only successful runs: `/gha subscribe oursky/github-actions-manager failure,timed_out`

**Comment by limouren** [comment]
I tried it out today. Seems multiple conclusions is not supported (`/gha subscribe oursky/github-actions-manager failure,timed_out`), but doing it individually works:

`/gha subscribe oursky/github-actions-manager failure`
`/gha subscribe oursky/github-actions-manager timed_out`

**Comment by kiootic** [comment]
I think it is space separated, try `/gha subscribe oursky/github-actions-manager failure timed_out`?

ref: https://github.com/oursky/github-actions-manager/blob/812b2cea11c957381031facec2c5586e6a2cc8bc/pkg/slack/app.go#L203-L218

**Comment by aekt** [comment]
Can we also support filtering by workflow/branch? Because want to ignore action results for CI and only notify on CD 😀

**Comment by cychiuae** [comment]
superseded by #21

**Comment by cychiuae** [comment]
I think this issue has served its purpose.
